'use client'
import Image from 'next/image'
import Link from 'next/link'
import { useEffect,useState } from 'react'
import { StoreShell } from '@/components/store-shell'
import { Checkout } from '@/components/checkout'
import { CartLine } from '@/lib/types'
import { formatIDR } from '@/lib/catalog'
export default function Cart(){const [lines,setLines]=useState<CartLine[]>([]);useEffect(()=>setLines(JSON.parse(localStorage.getItem('preloved-cart-v1')||'[]')),[]);function remove(id:string){const next=lines.filter(x=>x.id!==id);setLines(next);localStorage.setItem('preloved-cart-v1',JSON.stringify(next));window.dispatchEvent(new Event('cart-updated'))}const total=lines.reduce((n,x)=>n+(x.promoPrice??x.price)*x.quantity,0);return <StoreShell><section className="shell section"><p className="eyebrow">Keranjang</p><h1 style={{marginTop:4}}>Pesananmu</h1>{!lines.length?<p>Keranjang masih kosong. <Link href="/shop" style={{fontWeight:700,textDecoration:'underline'}}>Lihat barang</Link></p>:<div style={{display:'grid',gap:22,gridTemplateColumns:'minmax(0,1fr) minmax(240px,.42fr)'}}><div style={{display:'grid',gap:12}}>{lines.map(line=><article className="card" key={line.id} style={{display:'flex',gap:12,padding:10}}><div style={{position:'relative',width:80,aspectRatio:'4/5',overflow:'hidden',borderRadius:8}}><Image src={line.image} alt="" fill sizes="80px" style={{objectFit:'cover'}}/></div><div style={{flex:1}}><p className="eyebrow" style={{margin:0}}>{line.code}</p><strong>{line.name}</strong><p style={{margin:'5px 0'}}>{formatIDR(line.promoPrice??line.price)} × {line.quantity}</p><button onClick={()=>remove(line.id)} style={{border:0,background:'transparent',padding:0,color:'var(--danger)',fontWeight:700}}>Hapus</button></div></article>)}</div><aside className="card" style={{padding:18,height:'fit-content'}}><p style={{marginTop:0,color:'var(--muted)'}}>Subtotal</p><p style={{fontSize:'1.3rem',fontWeight:800,margin:'0 0 18px'}}>{formatIDR(total)}</p><Checkout lines={lines}/></aside></div>}</section></StoreShell>}
