'use client'
import Link from 'next/link'
import { useState } from 'react'
import { Check, Circle, Play, X } from 'lucide-react'

const steps=[
  {title:'Mulai dari katalog',text:'Gunakan Shop untuk melihat barang berdasarkan kategori dan harga.',href:'/shop',cta:'Buka Shop'},
  {title:'Baca detail dengan jujur',text:'Di halaman produk, cek kondisi, kode produk, foto, dan harga sebelum menambahkannya ke keranjang.',href:'/products/cardigan-rajut-biru',cta:'Lihat contoh produk'},
  {title:'Pesan tanpa checkout panjang',text:'Isi nama dan alamat, lalu lanjutkan percakapan untuk cek stok, ongkir, dan pembayaran di WhatsApp.',href:'/cart',cta:'Buka keranjang'},
  {title:'Titip Jual bila punya barang',text:'Kirim detail barang tanpa akun. Admin meninjau dan menentukan harga jual setelah kurasi.',href:'/titip-jual',cta:'Buka Titip Jual'},
]
export default function GetStarted(){const [active,setActive]=useState(false);const [done,setDone]=useState<number[]>([]);function finish(index:number){setDone(current=>current.includes(index)?current:[...current,index])}return <main className="shell section" style={{maxWidth:840}}><Link href="/brief" style={{fontWeight:700}}>← Kembali ke brief</Link><p className="eyebrow" style={{marginTop:28}}>Panduan interaktif</p><h1 style={{fontSize:'clamp(2.2rem,6vw,4rem)',letterSpacing:'-.06em',lineHeight:1,margin:'8px 0 16px'}}>Kenali alurnya,<br/>saat kamu siap.</h1><p style={{maxWidth:620,color:'var(--muted)'}}>Panduan ini tidak muncul otomatis. Aktifkan hanya bila kamu ingin menjelajahi fitur utama Preloved langkah demi langkah.</p>{!active?<section style={{marginTop:28,padding:20,border:'1px solid var(--line)',borderRadius:16,background:'var(--blue-soft)'}}><h2 style={{marginTop:0}}>Tur belum aktif</h2><p>Empat langkah singkat untuk memahami katalog, pesanan WhatsApp, dan Titip Jual.</p><button className="btn" onClick={()=>setActive(true)}><Play size={16}/> Mulai tour</button></section>:<section style={{marginTop:28}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:12,marginBottom:18}}><p style={{margin:0,fontWeight:700}}>{done.length} dari {steps.length} langkah selesai</p><button className="btn btn-secondary" onClick={()=>{setActive(false);setDone([])}}><X size={16}/> Akhiri tour</button></div><ol style={{listStyle:'none',padding:0,display:'grid',gap:12}}>{steps.map((step,index)=>{const complete=done.includes(index);return <li key={step.title} style={{display:'grid',gridTemplateColumns:'auto 1fr',gap:14,padding:18,border:'1px solid var(--line)',borderRadius:14,background:complete?'#f3faef':'#fffdf9'}}>{complete?<Check aria-label="Selesai" color="#48734c"/>:<Circle aria-hidden="true" color="var(--muted)"/>}<div><h2 style={{fontSize:'1.08rem',margin:'0 0 5px'}}>{index+1}. {step.title}</h2><p style={{margin:'0 0 13px',color:'var(--muted)'}}>{step.text}</p><Link href={step.href} onClick={()=>finish(index)} className="btn btn-secondary">{step.cta}</Link></div></li>})}</ol>{done.length===steps.length&&<div role="status" style={{marginTop:18,padding:18,borderRadius:14,background:'var(--pink-soft)'}}><strong>Tour selesai.</strong> Kamu sudah mengenal alur utama Preloved. <Link href="/home" style={{textDecoration:'underline',fontWeight:700}}>Mulai jelajahi storefront</Link>.</div>}</section>}</main>}
