create extension if not exists pgcrypto;
create type public.product_status as enum ('draft','available','reserved','sold','archived');
create type public.item_condition as enum ('like_new','very_good','good','fair');
create type public.consignment_status as enum ('pending','reviewing','approved','published','rejected','withdrawn','sold','settled');
create type public.profile_role as enum ('admin');
create type public.offer_discount_type as enum ('fixed_price','percentage');

create table public.profiles (id uuid primary key references auth.users on delete cascade, role public.profile_role not null default 'admin', display_name text, created_at timestamptz not null default now());
create table public.categories (id uuid primary key default gen_random_uuid(), name text not null unique, slug text not null unique, description text, sort_order integer not null default 0, is_active boolean not null default true);
create sequence public.product_code_seq start 1;
create table public.products (id uuid primary key default gen_random_uuid(), product_code text not null unique default ('PLV-' || lpad(nextval('public.product_code_seq')::text,4,'0')), slug text not null unique, name text not null, category_id uuid references public.categories, price_idr integer not null check(price_idr >= 0), description_short text not null check(char_length(description_short)<=180), description text not null, condition public.item_condition not null, status public.product_status not null default 'draft', is_highlighted boolean not null default false, published_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.product_images (id uuid primary key default gen_random_uuid(), product_id uuid not null references public.products on delete cascade, storage_path text not null, alt_text text not null, sort_order integer not null, width integer, height integer, unique(product_id,sort_order));
create table public.highlight_slides (id uuid primary key default gen_random_uuid(), image_path text not null, eyebrow text, title text not null, body text, cta_label text not null, cta_type text not null check(cta_type in ('product','category','offers','shop','url')), cta_target text not null, sort_order integer not null, is_active boolean not null default true, starts_at timestamptz, ends_at timestamptz);
create table public.offers (id uuid primary key default gen_random_uuid(), title text not null, summary text not null, banner_path text, discount_type public.offer_discount_type not null, amount integer not null check(amount>=0), starts_at timestamptz, ends_at timestamptz, is_active boolean not null default true);
create table public.offer_products (offer_id uuid references public.offers on delete cascade, product_id uuid references public.products on delete cascade, promo_price_idr integer check(promo_price_idr>=0), primary key(offer_id,product_id));
create table public.store_settings (id boolean primary key default true check(id), store_name text not null, whatsapp_number text not null check(whatsapp_number ~ '^[0-9]+$'), instagram_url text, contact_note text, updated_at timestamptz not null default now());
create table public.consignment_requests (id uuid primary key default gen_random_uuid(), seller_name text not null, seller_whatsapp text not null, seller_email text, product_name text not null, category_id uuid references public.categories, condition public.item_condition not null, description text not null, requested_net_price_idr integer not null check(requested_net_price_idr>=0), status public.consignment_status not null default 'pending', admin_feedback text, proposed_sale_price_idr integer check(proposed_sale_price_idr>=0), internal_margin_idr integer, published_product_id uuid references public.products, reviewed_by uuid references public.profiles, reviewed_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.consignment_request_images (id uuid primary key default gen_random_uuid(), request_id uuid not null references public.consignment_requests on delete cascade, storage_path text not null, sort_order integer not null, created_at timestamptz not null default now());
create table public.order_inquiries (id uuid primary key default gen_random_uuid(), buyer_name text not null, buyer_address text not null, subtotal_idr integer not null, status text not null default 'inquiry' check(status in ('inquiry','confirmed','shipped','completed','cancelled')), created_at timestamptz not null default now());
create index products_public_idx on public.products(status,published_at desc) where status in ('available','reserved','sold');
create index product_images_product_idx on public.product_images(product_id,sort_order);
create index consignments_queue_idx on public.consignment_requests(status,created_at desc);

alter table public.profiles enable row level security; alter table public.categories enable row level security; alter table public.products enable row level security; alter table public.product_images enable row level security; alter table public.highlight_slides enable row level security; alter table public.offers enable row level security; alter table public.offer_products enable row level security; alter table public.store_settings enable row level security; alter table public.consignment_requests enable row level security; alter table public.consignment_request_images enable row level security; alter table public.order_inquiries enable row level security;
create schema if not exists private;
create function private.is_admin() returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from public.profiles where id=(select auth.uid()) and role='admin')$$;
revoke all on function private.is_admin() from public;
grant usage on schema private to authenticated;
grant execute on function private.is_admin() to authenticated;
create policy "public reads active categories" on public.categories for select to anon,authenticated using(is_active);
create policy "public reads visible products" on public.products for select to anon,authenticated using(status in ('available','reserved','sold') and published_at is not null);
create policy "public reads product images" on public.product_images for select to anon,authenticated using(exists(select 1 from public.products p where p.id=product_id and p.status in ('available','reserved','sold') and p.published_at is not null));
create policy "public reads active slides" on public.highlight_slides for select to anon,authenticated using(is_active and (starts_at is null or starts_at<=now()) and (ends_at is null or ends_at>=now()));
create policy "public reads active offers" on public.offers for select to anon,authenticated using(is_active and (starts_at is null or starts_at<=now()) and (ends_at is null or ends_at>=now()));
create policy "public reads settings" on public.store_settings for select to anon,authenticated using(true);
create policy "users read own profile" on public.profiles for select to authenticated using((select auth.uid())=id);
create policy "admins full profiles" on public.profiles for all to authenticated using(private.is_admin()) with check(private.is_admin());
create policy "admins full categories" on public.categories for all to authenticated using(private.is_admin()) with check(private.is_admin());
create policy "admins full products" on public.products for all to authenticated using(private.is_admin()) with check(private.is_admin());
create policy "admins full product images" on public.product_images for all to authenticated using(private.is_admin()) with check(private.is_admin());
create policy "admins full slides" on public.highlight_slides for all to authenticated using(private.is_admin()) with check(private.is_admin());
create policy "admins full offers" on public.offers for all to authenticated using(private.is_admin()) with check(private.is_admin());
create policy "admins full offer products" on public.offer_products for all to authenticated using(private.is_admin()) with check(private.is_admin());
create policy "admins full settings" on public.store_settings for all to authenticated using(private.is_admin()) with check(private.is_admin());
create policy "admins full consignments" on public.consignment_requests for all to authenticated using(private.is_admin()) with check(private.is_admin());
create policy "admins full consignment images" on public.consignment_request_images for all to authenticated using(private.is_admin()) with check(private.is_admin());
create policy "admins full inquiries" on public.order_inquiries for all to authenticated using(private.is_admin()) with check(private.is_admin());

insert into storage.buckets (id,name,public,file_size_limit,allowed_mime_types) values ('public-assets','public-assets',true,5242880,array['image/jpeg','image/png','image/webp']),('consignment-private','consignment-private',false,5242880,array['image/jpeg','image/png','image/webp']) on conflict (id) do nothing;
create policy "admins manage public assets" on storage.objects for all to authenticated using(bucket_id='public-assets' and private.is_admin()) with check(bucket_id='public-assets' and private.is_admin());
create policy "admins manage private consignment assets" on storage.objects for all to authenticated using(bucket_id='consignment-private' and private.is_admin()) with check(bucket_id='consignment-private' and private.is_admin());
